export const forbiddenKeywords = [
  'porn', 'xxx', 'sex', 'facebook', 'tiktok', 'instagram', 'juegos', 'game', 'xvideos', 'xnxx', 'y8', "porn", "xxx", "sex", "xvideos", "xnxx", "redtube", "youporn", "brazzers", "youjizz", "pornhub", "hentai", "erotic", "adult", "nsfw", "camgirl", "cam4", "onlyfans", "fap", "nude", "escort", "livejasmin", "stripchat", "badoink", "lust", "bangbros", "tushy", "nudity", "climax", "anal", "facebook", "instagram", "tiktok", "snapchat", "twitter", "x.com", "whats", "messenger", "telegram", "reddit", "pinterest", "linkedin", "discord", "wechat", "line.me", "threads", "game", "games", "gamer", "juego", "juegos", "roblox", "fortnite", "minecraft", "steam", "epicgames", "valorant", "leagueoflegends", "lol", "riotgames",  "xbox", "nintendo", "pokemon", "callofduty", "counterstrike", "csgo", "dota", "pubg", "freefire", "garena", "twitch", 'porn', 'xxx', 'sex', 'facebook', 'tiktok', 'instagram', 'juegos', 'game',
  'xvideos', 'xnxx', 'y8', 'redtube', 'youporn', 'brazzers', 'youjizz', 'pornhub', 'hentai',
  'erotic', 'adult', 'nsfw', 'camgirl', 'cam4', 'onlyfans', 'fap', 'nude', 'escort', 'livejasmin',
  'stripchat', 'badoink', 'lust', 'bangbros', 'tushy', 'nudity', 'climax', 'anal', 'snapchat',
  'twitter', 'x.com', 'whats', 'messenger', 'telegram', 'reddit', 'pinterest', 'linkedin',
  'discord', 'wechat', 'line.me', 'threads', 'games', 'gamer', 'juego', 'roblox', 'fortnite',
  'minecraft', 'steam', 'epicgames', 'valorant', 'leagueoflegends', 'lol', 'riotgames', 'xbox',
  'nintendo', 'pokemon', 'callofduty', 'counterstrike', 'csgo', 'dota', 'pubg', 'freefire','patria', 'provincial','provinet', 'bdv','mercantil'
  , 'garena', 'twitch',
  '3movs', 'alphaporno', 'analdin', 'assparade', 'azporn', 'babes.com', 'badjojo', 'beeg','mercantil',
  'bestporn', 'bestpornsites', 'bestpornvideos', 'bestpornhub', 'bestpornhd', 'bestpornmovies',
  'bestgore', 'bigass', 'bigtits', 'blackporn', 'boyfriendtv', 'bravoporn', 'busty', 'cumlouder',
  'czechcasting', 'czechav', 'devilslust', 'drtuber', 'efukt', 'empflix', 'eurosex', 'extremetube',
  'femjoy', 'fleshlight', 'fuq', 'fux', 'gagfactor', 'gaytube', 'girlsdoporn', 'hardsextube',
  'hellporno', 'hclips', 'hdporn', 'hdtube', 'hot-sex-tube', 'iceporn',
  'xbox', 'xboxlive', 'xboxstore', 'psn', 'ps5', 'ps4', 'nintendo', 'switch', '3ds', 'ds',
  'wii', 'wiiu', 'gamecube', 'n64', 'gba', 'gbc', 'pokemon', 'mario', 'zelda', 'splatoon', 'metroid', 'kirby',
  'roblox', 'minecraft', 'fortnite', 'valorant', 'leagueoflegends', 'lol', 'overwatch', 'csgo', 'dota2', 'pubg',
  'freefire', 'garena', 'apexlegends', 'genshinimpact', 'honkaistarrail', 'cod', 'callofduty', 'warzone',
  'mobilelegends', 'arenaofvalor', 'smite', 'paladins', 'brawlhalla', 'rocketleague', 'amongus', 'fallguys',
  'rainbowsix', 'halo', 'eldenring', 'hogwartslegacy', 'spidermanps5', 'reddeadredemption', 'gta5', 'gtaonline',
  'fifa', 'nba2k', 'madden', 'thecrew', 'forzahorizon', 'forzamotorsport', 'gran-turismo', 'projectcars',
  'simracing', 'iracing', 'beamng', 'trackmania', 'needforspeed', 'burnout', 'midnightclub', 'nfs', 'assetto',
  'farming simulator', 'euro truck', 'american truck', 'flight simulator', 'dcs', 'arma3', 'dayz', 'rust',
  'conanexiles', 'ark', 'subnautica', 'terraria', 'stardewval', 'hades', 'hollowknight', 'celeste',
  'undertale', 'bindingofisaac', 'slaythespire', 'loophero', 'deadcells', 'riskofrain', 'limbo', 'inside',
  'littlebigplanet', 'cuphead', 'limbuscompany', 'thequarry', 'untildawn', 'detroitbecomehuman',
  'heavy rain', 'lifeisstrange', 'tellmewhy', 'telltale', 'walkingdeadgame', 'batman', 'gamepass', 'apkmod', 'apkpure', 'uptodown', 'emuparadise', 'coolrom', 'vimm', 'romsmania', 'romsgames',
  'romhustler', 'romnation', 'romsite', 'mame', 'snes9x', 'dolphin emulator', 'cemu', 'yuzu', 'youtube','ryujinx',
  'pcsx2', 'epsxe', 
  'proxygames', 'f95zone', 'adultgames', 'nsfwmods', 'lewdpatch', 'nutaku', 'hentaiheroes', 'porngame',
  'sexgames', 'dating sim', 'visualnovel', 'eroge', 'uncensoredpatch', 'animegame', 'adultpatch', 'yareel',"culo", "culos", "polla", "coño", "verga", "teta", "tetas", "chingar", "coger", "sexo",
  "follar", "mamada", "oral", "anal", "penetración", "desnudo", "desnuda", "pornografía",
  "porno", "puto", "puta", "putas", "lamida", "semén", "eyacular", "masturbarse",
  "ass", "asses", "dick", "pussy", "cock", "boobs", "tits", "fuck", "fucking", "sex",
  "nude", "nudes", "porn", "pornography", "blowjob", "handjob", "cum", "lick", "suck",
  "anal", "oral", "penetration", "jerk", "masturbate", "bitch", "slut", "nipple", "vagina",
  "penis", "horny", "nsfw", 'patria', 'youtube', "dinero facil", "click here", "subscribe", "suscribete", "follow me", "visit",
  "juego", "games", "casino", "gambling", "apuesta", "lottery", "loteria",
  "hack", "cracker", "phishing", "scam", "fraude", "robo", "pirateria", "pirate",
  "random", "test", "demo", "fake", "dummy", "beta",  "culo", "culos", "polla", "penis", "dick", "ass", "sex", "sexo", "s3xo", "p0rn", "porn", "porno", "fuck", "fuk", "f*ck",
  "idiota", "estupido", "imbecil", "tonto", "mierda", "bobo", "pendejo", "gilipollas",
  "cocaine", "marihuana", "weed", "marijuana", "drugs", "drogas", "cigarro", "cigarette", "alcohol", "beer",
  "gun", "arma", "kill", "matar", "bomba", "bomb", "shoot", "disparar", 'socialismo','muerte',  "adultsite1.com",
  "adultsite2.net",
  "adultcontent3.org",
  "xxxvideos.com",
  "pornhub.com",
  "redtube.com",
  "xvideos.com",
  "youjizz.com",
  "brazzers.com",
  "bangbros.com",
  "tube8.com",
  "youporn.com",
  "spankwire.com",
  "motherless.com",
  "porn.com",
  "tnaflix.com",
  "xhamster.com",
  "sunporno.com",
  "nuvid.com",
  "pornhd.com",
  "porndig.com",
  "empflix.com",
  "hclips.com",
  "xvideos2.com",
  "slutload.com",
  "beeg.com",
  "tube8.com",
  "vidz.com",
  "keezmovies.com",
  "sex.com",
  "lust.com",
  "fapdu.com",
  "drtuber.com",
  "eporner.com",
  "xtube.com",
  "pornrabbit.com",
  "pornhd.com",
  "sexyhub.com",
  "pornhere.com",
  "pornfun.com",
  "pornoxo.com",
  "pornflip.com",
  "nuvid.com",
  "pornhd.com",
  "yourporn.sexy",
  "pornmail.com",
  "gaytube.com",
  "hardsextube.com",
  "hqporner.com",
  "tubepornclassic.com",
  "pornoxo.com",
  "xxxhamster.com",
  "xvideoshub.com",
  "xhamster18.com",
  "xxxbunker.com",
  "pornhat.com",
  "porntube.com",
  "porncom.com",
  "drtuber.com",
  "xvideos2.com",
  "shameless.com",
  "porngo.com",
  "eporner.com",
  "tube8.com",
  "youporn.com",
  "pornhd.com",
  "spankwire.com",
  "motherless.com",
  "sexu.com",
  "bestpornsites.com",
  "freeporn.com",
  "pornmega.com",
  "pornhubpremium.com",
  "pornxxx.com",
  "xhamsterpremium.com",
  "youpornpremium.com",
  "tube8premium.com",
  "hclips.com",
  "brazzerspremium.com",
  "bangbrospremium.com",
  "porndig.com",
  "xxxnxx.com",
  "hotmovs.com",
  "pornofuck.com",
  "porn300.com",
  "onlyfans.com",
  "cams.com",
  "livejasmin.com",
  "chaturbate.com",
  "stripchat.com",
  "imlive.com",
  'machina','juegos','friv','minijuegos'

]